FROM python:3.12-slim

WORKDIR /app

COPY . /app/

RUN pip install --upgrade pip && \
    pip install pandas polars duckdb pytest pytest-cov ruff httpx fastapi && \
    pip install -e ".[dev,test]"

CMD ["/bin/bash", "-c", "ruff check src/ && ruff format --check src/ && pytest tests/ --cov=minilake"]
