name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Set up virtual environment
      run: |
        uv venv venv  # Explicitly create 'venv' directory
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        source venv/bin/activate  # Re-activate in each step
        uv pip install --upgrade pip
        uv pip install pylint  # Fixed: Install pylint here
    
    - name: Code analysis with pylint
      run: |
        source venv/bin/activate
        pylint $(git ls-files '*.py')  # Now pylint is available
