name: Ruff

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Set up virtual environment
      run: |
        uv venv venv
        source venv/bin/activate
    
    - name: Install dependencies
      run: |
        source venv/bin/activate
        uv pip install --upgrade pip
        uv pip install ruff pandas polars duckdb pytest
        uv pip install -e ".[dev]"
    
    - name: Run Ruff linting
      run: |
        source venv/bin/activate
        ruff check src/
    
    - name: Run Ruff formatting check
      run: |
        source venv/bin/activate
        ruff format --check src/
